/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/openapi.yaml": {
    /** This specification, as YAML */
    get: operations["getSpecYaml"];
  };
  "/openapi.json": {
    /** This specification, as JSON */
    get: operations["getSpecJson"];
  };
  "/buildings": {
    /** List the buildings this key can reach */
    get: operations["listBuildings"];
  };
  "/buildings/{buildingId}": {
    /** Get one building */
    get: operations["getBuilding"];
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
      };
    };
  };
  "/buildings/{buildingId}/rooms": {
    /**
     * List the rooms of a building
     * @description Each room includes the readings of its assigned sensor.
     */
    get: operations["listRooms"];
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
      };
    };
  };
  "/buildings/{buildingId}/rooms/{roomId}": {
    /** Get one room */
    get: operations["getRoom"];
    /**
     * Update room settings
     * @description Updates only the fields present in the body; everything else is left
     * alone. Requires the `buildings:write` permission.
     *
     * Changing a room's settings makes the heating engine recalculate that
     * room, so `power` and `heating` may change shortly after this call
     * returns. They cannot be set directly.
     */
    patch: operations["updateRoom"];
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
        roomId: components["parameters"]["RoomId"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Error: {
      error: {
        /** @enum {string} */
        code: "invalid_argument" | "unauthenticated" | "permission_denied" | "not_found" | "internal";
        message: string;
      };
    };
    Location: {
      /**
       * Format: double
       * @example 56.1629
       */
      lat?: number;
      /**
       * Format: double
       * @example 10.2039
       */
      lng?: number;
    } | null;
    Wind: {
      /**
       * @description Degrees, 0 is north.
       * @example 270
       */
      direction?: number;
      /**
       * @description Metres per second.
       * @example 4.2
       */
      speed?: number;
    } | null;
    /** @description Last observed outdoor conditions for the building. */
    Weather: ({
      /** Format: date-time */
      updated?: string | null;
      /** @description Degrees Celsius. */
      temperature?: number | null;
      /** @description Percent, 0-100. */
      cloud_coverage?: number | null;
      wind?: components["schemas"]["Wind"];
    }) | null;
    Building: {
      /** @example bbd508c9-42aa-4bc5-9981-a5b523d65aca */
      id: string;
      /** @example Hjemme */
      name?: string | null;
      location?: components["schemas"]["Location"];
      /** @description Whether the building's hardware has reported recently. null means no gateway has ever reported, which is not the same as offline. */
      available?: boolean | null;
      /**
       * Format: date-time
       * @description Newest heartbeat across the building's gateways.
       */
      last_seen?: string | null;
      weather?: components["schemas"]["Weather"];
    };
    /** @description Latest readings from the sensor assigned to the room. */
    Sensor: ({
      /**
       * @description The sensor's MAC address.
       * @example 58:2D:34:35:D5:A0
       */
      id: string;
      /**
       * @description Degrees Celsius.
       * @example 22.7
       */
      temperature?: number | null;
      /**
       * @description Relative humidity in percent.
       * @example 50.1
       */
      humidity?: number | null;
      /**
       * @description Battery level in percent.
       * @example 98
       */
      batt?: number | null;
      /**
       * @description Signal strength in dBm.
       * @example -88
       */
      rssi?: number | null;
      /**
       * Format: date-time
       * @description When the sensor last reported.
       */
      timestamp?: string | null;
    }) | null;
    /** @description Overrides the computed heating power for the room. */
    ManualPower: {
      /** @example false */
      enabled?: boolean;
      /**
       * Format: double
       * @description Share of the time the valve is held open, from 0 to 1 - see the power field on Room. Only used when enabled is true.
       */
      power?: number | null;
    };
    /** @description A room, shaped like a Home Assistant climate entity. */
    Room: {
      /** @example 5e2db47e-474c-4591-90ca-ba8d033612d1 */
      id: string;
      /** @example Stue */
      name?: string | null;
      /**
       * @description Latest temperature from the room's sensor, in degrees Celsius.
       * @example 22.7
       */
      current_temperature?: number | null;
      /**
       * @description Latest relative humidity from the room's sensor, in percent.
       * @example 50.1
       */
      current_humidity?: number | null;
      /**
       * @description The temperature the room is aiming for, in degrees Celsius.
       * @example 21.5
       */
      target_temperature?: number | null;
      /**
       * @description Lowest settable target temperature.
       * @example 7
       */
      min_temp?: number;
      /**
       * @description Highest settable target temperature.
       * @example 35
       */
      max_temp?: number;
      /**
       * @description "off" means the room is held at zero power. Writing this field is the way to stop or restart a room.
       * @enum {string}
       */
      hvac_mode?: "heat" | "off";
      hvac_modes?: readonly ("heat" | "off")[];
      /**
       * @description What the room is doing now. "idle" means on but not currently calling for heat; "off" means the room is stopped.
       * @enum {string}
       */
      hvac_action?: "heating" | "idle" | "off";
      /** @enum {string|null} */
      preset_mode?: "none" | "low" | "medium" | "high" | null;
      preset_modes?: readonly ("none" | "low" | "medium" | "high")[];
      manual_power?: components["schemas"]["ManualPower"];
      /**
       * @description How much of the time the heating is open. The controller opens and closes the actuator within a fixed time window, and this value is the share of that window the valve stays open: 0.5 means open half the time. The window length depends on the room's floor type and on system configuration.
       * @example 0.42
       */
      power?: number | null;
      /**
       * @description Id of the assigned sensor.
       * @example 58:2D:34:35:D5:A0
       */
      sensor_id?: string | null;
      sensor?: components["schemas"]["Sensor"];
    };
    /**
     * @description Only these fields can be written. Any other field in the body is
     * rejected with `400` rather than silently ignored.
     *
     * Sending both `hvac_mode` and `manual_power` applies `hvac_mode` last, so
     * the result does not depend on key order.
     */
    RoomUpdate: {
      name?: string;
      target_temperature?: number;
      /** @enum {string} */
      preset_mode?: "none" | "low" | "medium" | "high";
      /** @enum {string} */
      hvac_mode?: "heat" | "off";
      manual_power?: components["schemas"]["ManualPower"];
      /** @description Must be a sensor that exists in the same building. */
      sensor_id?: string;
    };
  };
  responses: {
    /** @description The request body failed validation. */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The API key is missing. */
    Unauthenticated: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The key is unknown, disabled, or lacks the required permission. */
    Forbidden: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description No such resource, or it is not covered by this key. */
    NotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /**
     * @description The building's id.
     * @example bbd508c9-42aa-4bc5-9981-a5b523d65aca
     */
    BuildingId: string;
    /**
     * @description The room's id.
     * @example 5e2db47e-474c-4591-90ca-ba8d033612d1
     */
    RoomId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** This specification, as YAML */
  getSpecYaml: {
    responses: {
      /** @description The OpenAPI document */
      200: {
        content: {
          "application/yaml": string;
        };
      };
    };
  };
  /** This specification, as JSON */
  getSpecJson: {
    responses: {
      /** @description The OpenAPI document */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** List the buildings this key can reach */
  listBuildings: {
    responses: {
      /** @description The buildings covered by the key. Empty if it covers none. */
      200: {
        content: {
          "application/json": components["schemas"]["Building"][];
        };
      };
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
    };
  };
  /** Get one building */
  getBuilding: {
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
      };
    };
    responses: {
      /** @description The building */
      200: {
        content: {
          "application/json": components["schemas"]["Building"];
        };
      };
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * List the rooms of a building
   * @description Each room includes the readings of its assigned sensor.
   */
  listRooms: {
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
      };
    };
    responses: {
      /** @description The rooms of the building */
      200: {
        content: {
          "application/json": components["schemas"]["Room"][];
        };
      };
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  /** Get one room */
  getRoom: {
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
        roomId: components["parameters"]["RoomId"];
      };
    };
    responses: {
      /** @description The room */
      200: {
        content: {
          "application/json": components["schemas"]["Room"];
        };
      };
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Update room settings
   * @description Updates only the fields present in the body; everything else is left
   * alone. Requires the `buildings:write` permission.
   *
   * Changing a room's settings makes the heating engine recalculate that
   * room, so `power` and `heating` may change shortly after this call
   * returns. They cannot be set directly.
   */
  updateRoom: {
    parameters: {
      path: {
        buildingId: components["parameters"]["BuildingId"];
        roomId: components["parameters"]["RoomId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoomUpdate"];
      };
    };
    responses: {
      /** @description The updated room */
      200: {
        content: {
          "application/json": components["schemas"]["Room"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
}
